Standardize formatting & add linting

diff --git a/bin/add_user b/bin/add_user
--- a/bin/add_user
+++ b/bin/add_user
@@ -2,31 +2,29 @@
 
 programname=$0
 
-function usage {
-    echo "usage: $programname <file>"
-    echo "Adds LDAP entries from ldif file."
-    exit 1
+function usage() {
+	echo "usage: $programname <file>"
+	echo "Adds LDAP entries from ldif file."
+	exit 1
 }
 
-if [ "$#" -ne 1 ]
-then
-  usage
+if [ "$#" -ne 1 ]; then
+	usage
 fi
 
-if [ ! -f $1 ]; then
-    echo "File not found!"
-    usage
+if [ ! -f "$1" ]; then
+	echo "File not found!"
+	usage
 fi
 
-PARDIR=$(dirname $(dirname $(realpath "$0")))
-source ${PARDIR}/.env
-
-
+PARDIR="$(dirname "$(dirname "$(realpath "$0")")")"
+# shellcheck source=/dev/null
+source "${PARDIR}"/.env
 
 docker-compose run \
-    --rm \
-    -v $(realpath $1):/tmp/ldapadd.ldif \
-    -v ${PARDIR}/authelia/_add_user.sh:/tmp/add_user.sh \
-    --entrypoint="/bin/bash" \
-    openldap \
-    /tmp/add_user.sh
+	--rm \
+	-v "$(realpath "$1")":/tmp/ldapadd.ldif \
+	-v "${PARDIR}"/authelia/_add_user.sh:/tmp/add_user.sh \
+	--entrypoint="/bin/bash" \
+	openldap \
+	/tmp/add_user.sh
